---
title: "Score Card"
date: "4/12/2020"
output: word_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(readxl)
library(knitr)
library(RColorBrewer)
options(digits = 2)
Log_Sheet <- read_csv(file.path(getwd(),"Data","Log Sheet.csv"),skip = 5)
colnames(Log_Sheet) <- colnames(Log_Sheet) %>% str_replace_all(.," ","_") %>% str_replace_all(.,"-","")
Log_Sheet <- Log_Sheet %>% mutate(Request_Recieved = c(sample(seq.Date(dmy("01/01/2020"),dmy("31/01/2020"),by="day"),4),
                                         sample(seq.Date(dmy("01/02/2020"),dmy("28/02/2020"),by="day"),4),
                                         sample(seq.Date(dmy("01/03/2020"),dmy("31/03/2020"),by="day"),4),
                                         sample(seq.Date(dmy("01/04/2020"),dmy("30/04/2020"),by="day"),4)),
                     Request_Prepared = Request_Recieved + days(round(rpois(1,1),0)),
                     Request_Completed = c(Request_Prepared[1:4] + days(round(rpois(1,6),0)),
                                           Request_Prepared[5:8] + days(round(rpois(1,3),0)),
                                           Request_Prepared[9:12] + days(round(rpois(1,2),0)),
                                           Request_Prepared[13:16] + days(round(rpois(1,2),0))))

Log_Sheet[16,"Request_Prepared"] <- NA
Log_Sheet[16,"Request_Completed"] <- NA
Log_Sheet[15,"Request_Completed"] <- NA
Log_Sheet <- Log_Sheet %>% mutate(Month = month(Request_Recieved,label = TRUE))
```

```{r Score Card}
Log_Sheet %>% mutate(Time = (Request_Completed - Request_Recieved) <=3) %>% 
  summarise(`% Requests Completed` = mean(Time,na.rm = TRUE) * 100, `Average Time for request completion` = round(mean(Request_Completed - Request_Recieved,na.rm = T),0)) %>% gather(key = "KPI", value = "Score") %>% kable()
```